name: "fetch open issues"
on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 12 * * *'  # Runs at 12 PM every day
  
jobs:
  fetch_issues:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
       
      - name: setup python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
       
      - name: install dependencies
        run: |
         python -m pip install --upgrade pip
         pip install requests pygithub coverage flake8 black 
      - name: Run the script
        run: |
         python /scripts/fetch_info.py
         python /scripts/test_github_fetch.py
         flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
         flake8 . --count --exit-zero --max-complexity=10 --max-line-length=88 --statistics 
         coverage run test_github_fetch.py
         coverage report --fail-under=80 --show-missing --skip-covered
         coverage html
      

        env:
         GITHUB_TOKEN: ${{ secrets.TOKEN }}