name: "fetch open issues"
on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 12 * * *'  # Runs at 12 PM every day
  
jobs:
  fetch_issues:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
       
      - name: setup python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
       
      - name: install dependencies
        run: |
         python -m pip install --upgrade pip
         pip install requests pygithub coverage
      - name: Run the script
        run: |
         python fetch_info.py
         python test_github_fetch.py

        env:
         GITHUB_TOKEN: ${{ secrets.TOKEN }}